defaults: &defaults
  # resource_class: xlarge
  docker:
    - image: circleci/node:10.0.0
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: npm install
      - run:
          name: test.ci.before
          command: npm run test.ci.before
      - run:
          name: test.ci.after
          command: npm run test.ci.after
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: npm install
      - run:
          name: Lint
          command: npm run lint
  bundlesize:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: npm install
      - run:
          name: Bundlesize
          command: npm run start.prod.ci.aot && npm run bundlesize
  unit_tests:
    <<: *defaults
    environment:
      TEST_REPORT_FILENAME: "test-results.xml"
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: npm install
      - run:
          name: Generate App Config
          command: npm run test.ci.before
      - run:
          name: Test
          command: npm run test.client -- --ci --updateSnapshot --maxWorkers=1 --coverage
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
      - run:
          name: Post coverage results
          command: bash <(curl -s https://codecov.io/bash)
  e2e_tests:
    <<: *defaults
    docker:
      - image: circleci/node:9.9-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: npm install
      - run:
          name: Test
          command:  npm run test.e2e.ci.aot
  semver:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: npm install
      - run:
          name: Semantic Release
          command: npm run semantic-release || true
workflows:
  version: 2
  build_test_release:
    jobs:
      - build
      - unit_tests:
          requires:
            - build
    #   - e2e_tests:
    #       requires:
    #         - build
      - lint:
          requires:
            - build
      - bundlesize:
          requires:
            - build
    #   - semver:
    #       requires:
    #         - build
    #         - unit_tests
    #         - e2e_tests
    #         - lint
    #         - bundlesize
    #       filters:
    #         branches:
    #           only: master
    #   - deploy:
    #       requires:
    #         - build
    #         - unit_tests
    #         - e2e_tests
    #         - lint
    #         - bundlesize
    #       filters:
    #         branches:
    #           only: master